// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

 

// ...


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXWCiRkTAn-PeHpOn0zuLwQ-D11uVR-J0',
    appId: '1:547918022030:web:ee2d3a58df9ceea03010df',
    messagingSenderId: '547918022030',
    projectId: 'flash-chat-acefd',
    authDomain: 'flash-chat-acefd.firebaseapp.com',
    storageBucket: 'flash-chat-acefd.firebasestorage.app',
    measurementId: 'G-L1XZG76QV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvUwq8-qPJa3sA6QL-m683BxRxxbShr5E',
    appId: '1:547918022030:android:cdfec4768a56c10b3010df',
    messagingSenderId: '547918022030',
    projectId: 'flash-chat-acefd',
    storageBucket: 'flash-chat-acefd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEwCLeouQvmowXPzK5IAtLjlvPdNLRgHo',
    appId: '1:547918022030:ios:2700df1b043402a03010df',
    messagingSenderId: '547918022030',
    projectId: 'flash-chat-acefd',
    storageBucket: 'flash-chat-acefd.firebasestorage.app',
    iosBundleId: 'com.example.flashChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEwCLeouQvmowXPzK5IAtLjlvPdNLRgHo',
    appId: '1:547918022030:ios:2700df1b043402a03010df',
    messagingSenderId: '547918022030',
    projectId: 'flash-chat-acefd',
    storageBucket: 'flash-chat-acefd.firebasestorage.app',
    iosBundleId: 'com.example.flashChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXWCiRkTAn-PeHpOn0zuLwQ-D11uVR-J0',
    appId: '1:547918022030:web:a5b51eb46ba003e93010df',
    messagingSenderId: '547918022030',
    projectId: 'flash-chat-acefd',
    authDomain: 'flash-chat-acefd.firebaseapp.com',
    storageBucket: 'flash-chat-acefd.firebasestorage.app',
    measurementId: 'G-V0JXVCB3YD',
  );
}


